### ISSUE TITLE
Use "queryst" library to decode nested query strings

### ISSUE THREAD

**Issue by s-panferov** [iron/urlencoded#37]
Just look at https://github.com/rustless/queryst, maybe you can use it to cover some complex cases.

**Comment by reem** [comment]
Is this a standard thing? I'm generally going to avoid putting in features if they aren't a standard feature for a library like this one.

**Comment by s-panferov** [comment]
@reem it parses query string the same way Rails does. And it's the same format that jQuery uses in it's [.param()](http://api.jquery.com/jquery.param/). So I think it's quite standard. There is no RFC of course. But I don't insist, I've just wanted to show you the library.

**Comment by reem** [comment]
I think this is the kind of thing I would be happy to have as an external library - there's no reason this has to support every use case.
