### ISSUE TITLE
Proper support for arrays

### ISSUE THREAD

**Issue by RoxasShadow** [iron/urlencoded#59]
Both the urlencoded crate and the rust compiler are versioned at the most recent stable releases.

**Current behavior**
`/?key[]=val1&key[]=val2` => `{"key[]": ["1", "2"]}`

**Suggested behavior**
`/?key[]=val1&key[]=val2` => `{"key": ["1", "2"]}`

**Currently supported behavior**
`/?key=val1&key=val2` => `{"key": ["1", "2"]}`

This topic doesn't seem really [clear](https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string) to everyone, but I'm pretty sure that the suggested one is the most common behavior (see Rails or PHP, for example).

**Comment by SkylerLipthay** [comment]
For what it's worth, this opinionated functionality exists as you describe it in [iron/params](https://github.com/iron/params/blob/master/src/lib.rs#L216).

I personally prefer leaving urlencoded as-is to avoid breaking changes and to leave this decision up to the crate user.

**Comment by RoxasShadow** [comment]
iron/params works perfectly for what I need. We can keep this crate as it is. Thanks!
